### PR TITLE
added a basic signing provider with SGX enclave app backend

### PR DESCRIPTION
**Pull request by tomtau**
- communication exchange via usercall extension
(enclave needs to be built with https://edp.fortanix.com/ )
- sealing/kewrapping via AES-GCM-SIV

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
Sorry, haven't had time to review this yet. Will take a look after we get Signatory updated to new dependencies (#57)

**Comment by tony-iqlusion** [comment]
FYI, we've cut another Signatory release. If you can rebase, we can review this now.

**Comment by tomtau** [comment]
it's rebased now

**Comment by tony-iqlusion** [comment]
Let me start by saying this looks really interesting and I'd like to figure out how to get it integrated into Tendermint KMS.

I've opened a bit of a meta-question issue about the future of Signatory where I mention this PR, and I'd like to know your thoughts on that:

https://github.com/iqlusioninc/signatory/issues/71

Specifically I think it might make sense to integrate this code directly into the [Tendermint KMS](https://github.com/iqlusioninc/tmkms) repo, with the longer-term goal of adding more intelligent signature validation code and chain state tracking in the enclave app, rather than adding it to Signatory. Per the above issue, we may consider winding down Signatory altogether.

**Comment by tony-iqlusion** [comment]
Seems this work is continuing in `tmkms-light`.

**Pull request closed without merging**
